# Generated by Django 4.1.6 on 2023-02-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='playerChoice',
            field=models.CharField(default='', max_length=50),
        ),
    ]
