# Generated by Django 4.1.6 on 2023-02-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_question_playerchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='playerChoice',
            field=models.BooleanField(default=False),
        ),
    ]
