# Generated by Django 4.1.6 on 2023-02-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_quiz_completed_alter_question_playerchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='playerChoice',
            field=models.CharField(default='', max_length=50),
        ),
    ]
